### ISSUE TITLE
搜索百度百科获取不到结果时 IndexError 的处理

### ISSUE THREAD

**Issue by zxjsdp** [zxjsdp/LatinSearch#49]

**Comment by zxjsdp** [comment]
```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk/Tkinter.py", line 1536, in __call__
    return self.func(*args)
  File "latinsearch.py", line 1471, in _query_baidu_baike
    InternetQuery.search_baidu_baike(keyword))
  File "latinsearch.py", line 702, in search_baidu_baike
    first_baike_url = outcomes[0].find(href=True).get('href')
IndexError: list index out of range
```
